### PR TITLE
JuMP 0.20 and Julia ≥ 1.2

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by matbesancon** [comment]
@amontoison thanks, replaced by #55

**Comment by matbesancon** [comment]
(I'll still add the most recent julia versions to travis)

**Comment by amontoison** [comment]
Thanks @matbesancon ! Do you want that I update #48 ? We prepared some tutorials with @mtanneau but no one found time to review them.

**Comment by matbesancon** [comment]
Yes that would be a great addition thanks!

**Pull request closed without merging**
