### PR TITLE
minor formatting and improvement

### PR DESCRIPTION
**Pull request by matbesancon**
Not much here, minor improvements on formatting and adding a const where it makes sense

### CODE REVIEW

**Review by odow — APPROVED** [review]
I guess we need to update the Compat in Project.toml first.

**Comment by matbesancon** [comment]
Yes I wanted to get this out of the way but it seems even the current state of the Manifest does not resolve to a feasible package version

**Comment by matbesancon** [comment]
@odow adding compat to pass tests is not necessary, since the tutorials use the manifest. As long as one does not run ]up we maintain the same state. My last commit makes the minimal Manifest changes to make the resolver happy

**Comment by matbesancon** [comment]
the compat bounds are in the next PRs

**Pull request merged**
