### PR TITLE
cleanup src files

### PR DESCRIPTION
**Pull request by matbesancon**
using Weave in the src files caused errors, they are not used anymore since conversion is now done in the `converter` sub-project

### CODE REVIEW

**Review by odow — APPROVED** [review]
If you have time, we're probably better off making edits to the tutorials I started migrating to JuMP.jl: https://jump.dev/JuMP.jl/dev/tutorials/Getting%20started/an_introduction_to_julia/, or migrating some of the `modeling` ones that I haven't done yet.

**Comment by matbesancon** [comment]
> we're probably better off making edits to the tutorials I started migrating to JuMP.jl

yes I agree, this was mostly to have the repo in a clean state (non-failing) and close all the compat PRs

**Comment by ferrolho** [comment]
> conversion is now done in the `converter` sub-project

Can you explain this in more detail?

Previously, to generate the test and notebook files programmatically I ran:
```julia
using JuMPTutorials
JuMPTutorials.weave_file("modelling", "space_shuttle_reentry_trajectory.jl")
```

Now, I did the following:
```julia
# First, navigate to the folder `JuMPTutorials.jl/converter`
]activate .
include("convert_pages.jl")
generate_output()
```

Is this the way we are supposed to do it?

**Comment by matbesancon** [comment]
yes exactly.

**Pull request merged**
